[package]
name = "json_parser_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.128"
serde = "1.0.210"
serde_stacker = "0.1.11"
serde_derive = "1.0.199"

jsonschema = "0.18"

log = "0.4.22"
regex = "1.10.6"
