[workspace]
resolver = "2"

members = [ 
    "json_parser_app",
    "json_parser_lib"
]

#[[bin]]
#name = "json_parser_app"
#path = "./json_parser_app/src/main.rs"
#required-features = ["cargo"]
#doc-scrape-examples = true